## For more details on how to configure your build environment visit
# http://www.gradle.org/docs/current/userguide/build_environment.html
#
# Specifies the JVM arguments used for the daemon process.
# The setting is particularly useful for tweaking memory settings.
# Default value: -Xmx1024m -XX:MaxPermSize=256m
# org.gradle.jvmargs=-Xmx2048m -XX:MaxPermSize=512m -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8
#
# When configured, Gradle will run in incubating parallel mode.
# This option should only be used with decoupled projects. For more details, visit
# https://developer.android.com/r/tools/gradle-multi-project-decoupled-projects
# org.gradle.parallel=true
#Sun Apr 27 08:21:02 WEST 2025

# kotlin.incremental.useClasspathSnapshot=true
# org.gradle.jvmargs=-Xmx3g -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8
# kotlin.daemon.jvm.options="-Xmx1g"

# org.gradle.jvmargs=-Xmx3g -XX:+UseG1GC -XX:MaxGCPauseMillis=100 -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8

# org.gradle.jvmargs=-Xmx2g -XX:+UseG1GC -XX:+UnlockExperimentalVMOptions -XX:G1NewSizePercent=20 -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8
org.gradle.jvmargs=-Xmx2g -XX:+UseG1GC -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8
kotlin.daemon.jvm.options = -Xmx1g
kotlin.compiler.execution.strategy = daemon
# org.gradle.workers.isolation.default=none

android.enableJetifier=false
android.nonFinalResIds=true
android.nonTransitiveRClass=true
android.useAndroidX=true

org.gradle.caching=true
org.gradle.configuration-cache=true
org.gradle.parallel=false
org.gradle.workers.max=2

kotlin_version=2.4.20
krdb_version=3.3.6

android.dependency.useConstraints=false

# android.r8.enablePartitionMapOutput=true


android.enableR8.fullMode=false

